//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.06 at 02:42:21 PM IST 
//


package com.dxc.loantransaction.request;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.dxc.loantransaction.request package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TxLoan_QNAME = new QName("http://www.dxc.com/request/", "TxLoan");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.dxc.loantransaction.request
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TxLoan }
     * 
     */
    public TxLoan createTxLoan() {
        return new TxLoan();
    }

    /**
     * Create an instance of {@link IndexedData }
     * 
     */
    public IndexedData createIndexedData() {
        return new IndexedData();
    }

    /**
     * Create an instance of {@link TranDetails }
     * 
     */
    public TranDetails createTranDetails() {
        return new TranDetails();
    }

    /**
     * Create an instance of {@link WMAData }
     * 
     */
    public WMAData createWMAData() {
        return new WMAData();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TxLoan }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.dxc.com/request/", name = "TxLoan")
    public JAXBElement<TxLoan> createTxLoan(TxLoan value) {
        return new JAXBElement<TxLoan>(_TxLoan_QNAME, TxLoan.class, null, value);
    }

}
